server:
  port: 9102

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/medilabo
  cloud:
    gateway:
      routes:
        - id: microback
          uri: http://localhost:9001  # L'URI de microback
          predicates:
            - Path=/microback/**
          filters:
            - RemoveRequestHeader=Authorization
            - RelayTokenRequestFilter
        - id: medilabo-note
          uri: http://localhost:9003  # L'URI de medilabo-note
          predicates:
            - Path=/medilabo-note/**
          filters:
            - RemoveRequestHeader=Authorization
            - RelayTokenRequestFilter
        - id: medilabo-report
          uri: http://localhost:9004  # L'URI de medilabo-report
          predicates:
            - Path=/medilabo-report/**
          filters:
            - RemoveRequestHeader=Authorization
            - RelayTokenRequestFilter