server:
  port: 9102

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/medilabo
  cloud:
    gateway:
      routes:
        - id: microback
          uri: http://localhost:9001  # L'URI de votre service backend
          predicates:
            - Path=/microback/**
          filters:
            - RemoveRequestHeader=Authorization
            - RelayTokenRequestFilter
        - id: service2
          uri: http://localhost:9003  # L'URI d'un autre service backend
          predicates:
            - Path=/medilabo-note/**
          filters:
            - RemoveRequestHeader=Authorization
            - RelayTokenRequestFilter