services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - '8761:8761'
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - '9101:9101'
    networks:
      - spring-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9101/actuator/health"]
      interval: 30s       # Intervalle entre les tests
      timeout: 10s        # Temps maximum pour qu'une réponse soit reçue
      retries: 3          # Nombre de tentatives avant de marquer le conteneur comme unhealthy
      start_period: 30s   # Temps d'attente avant de commencer les tests de santé

  gateway-server:
    build: ./gateway-server
    container_name: gateway-server
    ports:
      - '9102:9102'
    networks:
      - spring-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-server:9101
      - KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/medilabo
      - KEYCLOAK_CERTS=http://host.docker.internal:8080/realms/medilabo/protocol/openid-connect/certs
      - MICROBACK_URI_YML=http://microback:9001
      - NOTE_URI_YML=http://medilabo-note:9003
      - REPORT_URI_YML=http://medilabo-report:9004
      - MICROBACK_URI=lb://microback:9001
      - MEDILABO_NOTE_URI=lb://medilabo-note:9003
      - MEDILABO_REPORT_URI=lb://medilabo-report:9004
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9102/actuator/health"]
      interval: 30s       # Intervalle entre les tests
      timeout: 10s        # Temps maximum pour qu'une réponse soit reçue
      retries: 5          # Nombre de tentatives avant de marquer le conteneur comme unhealthy
      start_period: 60s   # Temps d'attente avant de commencer les tests de santé

  microback:
    build: ./microback
    container_name: microback
    ports:
      - '9001:9001'
    networks:
      - spring-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-server:9101
      - MYSQL_HOST=host.docker.internal
      - KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/medilabo
      - KEYCLOAK_CERTS=http://host.docker.internal:8080/realms/medilabo/protocol/openid-connect/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/actuator/health"]
      interval: 30s       # Intervalle entre les tests
      timeout: 10s        # Temps maximum pour qu'une réponse soit reçue
      retries: 5          # Nombre de tentatives avant de marquer le conteneur comme unhealthy
      start_period: 150s   # Temps d'attente avant de commencer les tests de santé

  medilabo-note:
    build: ./medilabo-note
    container_name: medilabo-note
    ports:
      - '9003:9003'
    networks:
      - spring-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-server:9101
      - MONGO_BD=host.docker.internal
      - SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017/patientnote
      - KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/medilabo
      - KEYCLOAK_CERTS=http://host.docker.internal:8080/realms/medilabo/protocol/openid-connect/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003/actuator/health"]
      interval: 30s       # Intervalle entre les tests
      timeout: 10s        # Temps maximum pour qu'une réponse soit reçue
      retries: 3          # Nombre de tentatives avant de marquer le conteneur comme unhealthy
      start_period: 150s   # Temps d'attente avant de commencer les tests de santé 
  
  medilabo-report:
    build: ./medilabo-report
    container_name: medilabo-report
    ports:
      - '9004:9004'
    networks:
      - spring-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-server:9101
      - KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/medilabo
      - KEYCLOAK_CERTS=http://host.docker.internal:8080/realms/medilabo/protocol/openid-connect/certs
      - MICROBACK=http://microback:9001
      - NOTE_URL=http://medilabo-note:9003
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9004/actuator/health"]
      interval: 30s       # Intervalle entre les tests
      timeout: 10s        # Temps maximum pour qu'une réponse soit reçue
      retries: 3          # Nombre de tentatives avant de marquer le conteneur comme unhealthy
      start_period: 150s   # Temps d'attente avant de commencer les tests de santé
  
  medilabo-frontend:
    build: ./medilabo-frontend
    container_name: medilabo-frontend
    ports:
      - '9002:9002'
    networks:
      - spring-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
      microback:
        condition: service_healthy
      medilabo-note:
        condition: service_healthy
      medilabo-report:
        condition: service_healthy
    environment:
      - MICROBACK_GATEWAY_URL=http://gateway-server:9102/microback
      - NOTE_GATEWAY_URL=http://gateway-server:9102/medilabo-note
      - REPORT_GATEWAY_URL=http://gateway-server:9102/medilabo-report
      - KEYCLOAK_TOKEN_URI=http://host.docker.internal:8080/realms/medilabo/protocol/openid-connect/token
      - KEYCLOAK_REVOKE_URI=http://host.docker.internal:8080/realms/medilabo/protocol/openid-connect/revoke

networks:
  spring-network:
    driver: bridge